repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.10
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.8.13
  hooks:
    - id: uv-lock # Update the uv lockfile

  # - repo: https://github.com/hadolint/hadolint
  #   rev: v2.12.0
  #   hooks:
  #     - id: hadolint-docker
  #       args: [--ignore, DL3008]  

  # - repo: https://github.com/adrienverge/yamllint # docker-compose linting
  #   rev: v1.37.1
  #   hooks:
  #     - id: yamllint
  #       files: docker-compose.*\.ya?ml$