FROM python:3.12-slim

WORKDIR /app

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    g++ \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN pip install --no-cache-dir \
    mlflow==3.1.4 \
    psycopg2-binary==2.9.10 \
    boto3==1.40.0

# Create directories for artifacts & runs. Give airflow full permission
RUN mkdir -p /mlflow/artifacts /mlflow/runs && chmod 777 /mlflow/artifacts
EXPOSE 5000

# Environment variables will be injected from docker-compose.yml
ENV MLFLOW_HOST=0.0.0.0
ENV MLFLOW_PORT=5000


# Use entrypoint instead of inline ENV credentials
CMD ["sh", "-c", "mlflow server \
    --backend-store-uri $MLFLOW_BACKEND_STORE_URI \
    --default-artifact-root $MLFLOW_DEFAULT_ARTIFACT_ROOT \
    --host $MLFLOW_HOST \
    --port $MLFLOW_PORT"]
